# Generated by Django 5.1.5 on 2025-02-02 15:09

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='The full question text')),
                ('answer', django_ckeditor_5.fields.CKEditor5Field(help_text='The detailed answer with formatting')),
                ('language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('bn', 'Bengali'), ('te', 'Telugu'), ('ta', 'Tamil'), ('ml', 'Malayalam'), ('kn', 'Kannada'), ('mr', 'Marathi'), ('gu', 'Gujarati'), ('pa', 'Punjabi'), ('ur', 'Urdu'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('it', 'Italian'), ('pt', 'Portuguese'), ('nl', 'Dutch'), ('ru', 'Russian'), ('zh-cn', 'Chinese (Simplified)'), ('zh-tw', 'Chinese (Traditional)'), ('ja', 'Japanese'), ('ko', 'Korean'), ('vi', 'Vietnamese'), ('th', 'Thai'), ('ar', 'Arabic'), ('fa', 'Persian'), ('tr', 'Turkish'), ('id', 'Indonesian'), ('ms', 'Malay'), ('sw', 'Swahili')], default='en', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['-created_at'],
            },
        ),
    ]
